spring:
  profiles:
    active: dev

---
server:
  port: 8081

spring:
  profiles: dev
  application:
    name: springcloud-client-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 8082

spring:
  profiles: test
  application:
    name: springcloud-client-test
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/