spring:
  profiles:
    active: dev

---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: springcloud-config-dept-dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterUncoding=utf-8&serverTimeZone=UTC
    username: root
    password: 3456

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: xyz.hanfei.springcloud.pojo

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/
  instance:
    instance-id: springcloud-provider-8001 #修改 eureka 上的默认描述信息
    prefer-ip-address: true
    
info:
  app.name: hanfei.springcloud
  company.name: www.hanfei.xyz
  
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: springcloud-config-dept-test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterUncoding=utf-8&serverTimeZone=UTC
    username: root
    password: 3456

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: xyz.hanfei.springcloud.pojo

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/
  instance:
    instance-id: springcloud-provider-8001 
    prefer-ip-address: true

info:
  app.name: hanfei.springcloud
  company.name: www.hanfei.xyz  
